# This workflow will build, run unit tests on wpf application
# built on .NET Core.

name: .NET WPF Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: windows-latest
                             
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x   #Current WPF Target version is 8.0.x

    # Run CodeQL analysis
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
          languages: csharp
          build-mode:  manual

    - name: Dependency Review
      if: github.event_name == 'pull_request'
      uses: actions/dependency-review-action@v3

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build solution
      run: dotnet build --configuration Release --no-restore  

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Publish Application
      run: dotnet publish SimpleCalculator/SimpleCalculator.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:UseAppHost=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Calculator-App
        path: '**/bin/Release/net8.0-windows/*.exe'
        retention-days: 7 
